apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureorder
spec:
  selector:
      matchLabels:
        app: captureorder
  replicas: 2
  template:
      metadata:
        labels:
            app: captureorder
      spec:
        containers:
        - name: captureorder
          image: twuyacr.azurecr.io/captureorder:placeholdertag # replace with your own repository. Due to a bug, leave the :placeholdertag tag in there to allow the pipeline to replace it
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: TEAMNAME
            value: 'team-azch' # will be patched at deployment time by value of 'teamName' in the variable group
          - name: MONGOHOST
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoHost
          - name: MONGOUSER
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoUser
          ports:
          - containerPort: 80
          volumeMounts:
          - name: mongosecret
            mountPath: /kvmnt
            readOnly: true
        volumes:
          - name: mongosecret
            flexVolume:
              driver: "azure/kv"
              secretRef:
                name: kvcreds
              options:
                usepodidentity: "false"
                keyvaultname: twuy-aks-vault
                keyvaultobjectnames: mongo-password # Name of Key Vault secret
                keyvaultobjecttypes: secret
                resourcegroup: twuy-aks-weu
                subscriptionid: 4b197dc5-d690-41ca-8ad0-7940531674d3
                tenantid: 61261dd3-b1cd-4a90-b352-f162f961cf2b
